version: '3.6'
services:
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    networks:
      - main_net
    volumes:
      - mongodb_data_container:/data/db
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass 123456
    networks:
      - main_net
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - main_net
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9094:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    networks:
      - main_net
  kafka:
    image: docker.io/bitnami/kafka:3.3
    restart: always
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_KRAFT_CLUSTER_ID=my-cluster
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://kafka:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
      - main_net
  vp-minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    container_name: vp-minio
    privileged: true
    volumes:
      - ./minio/data:/data
      - ./minio/config:/root/.minio
    environment:
      MINIO_ROOT_USER: CRezL5QDT4d6WVlK
      MINIO_ROOT_PASSWORD: Ai808HBF3cHyHuKCPWiboe0oFIfgb9mc
    restart: always
    command: minio server /data --console-address ':9001'
    networks:
      - main_net
  nacos:
    image: nacos/nacos-server:v2.4.2
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
    ports:
      - "8880:8080"
      - "8848:8848"
      - "9848:9848"
    volumes:
      - ./nacos/logs:/home/nacos/logs
    restart: unless-stopped
    networks:
      - main_net

  sentinel-dashboard:
    image: bladex/sentinel-dashboard:1.8.8
    container_name: sentinel-dashboard
    ports:
      - "8858:8858"
    environment:
      - JAVA_OPTS=-Dserver.port=8858 -Dcsp.sentinel.dashboard.server=localhost:8858
    restart: unless-stopped
volumes:
  mongodb_data_container:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  minio_data:
    driver: local
networks:
  main_net:
    driver: bridge
